language: c
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.03.0+flambda
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.04.0+flambda
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - time
before_install:
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam install ocamlfind ocamlbuild
  - opam pin add dolmen https://github.com/Gbury/dolmen.git
install:
  - make bin lib
script:
  - make test
